import { EventDefinition } from './types';

export const eventDefinitions: EventDefinition[] = [
  {
    id: 'ai-boom',
    name: 'AI Boom',
    description: 'Massive AI breakthrough drives tech stocks soaring',
    impacts: {
      Technology: 0.08,
      Healthcare: 0.03,
      Entertainment: 0.02,
      Aerospace: 0.01,
      Industrial: 0.04,
      Telecom: 0.02,
    },
    color: '#22c55e',
  },
  {
    id: 'market-crash',
    name: 'Market Crash',
    description: 'Global panic triggers broad market selloff',
    impacts: {
      Technology: -0.06,
      Energy: -0.05,
      Healthcare: -0.04,
      Entertainment: -0.07,
      Aerospace: -0.05,
      Finance: -0.08,
      Materials: -0.04,
      Consumer: -0.06,
      Industrial: -0.05,
      Telecom: -0.03,
    },
    color: '#ef4444',
  },
  {
    id: 'energy-surge',
    name: 'Energy Surge',
    description: 'Energy crisis sends energy and materials stocks surging',
    impacts: {
      Energy: 0.10,
      Materials: 0.06,
      Aerospace: -0.02,
      Technology: -0.01,
      Industrial: 0.03,
    },
    color: '#f59e0b',
  },
  {
    id: 'fed-rate-cut',
    name: 'Fed Rate Cut',
    description: 'Federal Reserve announces surprise rate cut, boosting growth sectors',
    impacts: {
      Finance: 0.07,
      Technology: 0.05,
      Consumer: 0.06,
      Entertainment: 0.04,
      Industrial: 0.03,
      Aerospace: 0.02,
    },
    color: '#3b82f6',
  },
  {
    id: 'biotech-breakthrough',
    name: 'Biotech Breakthrough',
    description: 'Revolutionary gene therapy treatment receives FDA fast-track approval',
    impacts: {
      Healthcare: 0.12,
      Technology: 0.02,
      Finance: 0.01,
    },
    color: '#10b981',
  },
  {
    id: 'trade-war',
    name: 'Trade War Escalation',
    description: 'New tariffs imposed on major trading partners rattle markets',
    impacts: {
      Technology: -0.04,
      Consumer: -0.07,
      Industrial: -0.06,
      Materials: -0.05,
      Telecom: -0.02,
      Aerospace: -0.03,
      Entertainment: -0.02,
    },
    color: '#dc2626',
  },
  {
    id: 'space-contract',
    name: 'Space Mega-Contract',
    description: 'Government awards $50B space infrastructure contract',
    impacts: {
      Aerospace: 0.15,
      Technology: 0.04,
      Industrial: 0.05,
      Materials: 0.03,
      Telecom: 0.06,
    },
    color: '#8b5cf6',
  },
  {
    id: 'consumer-boom',
    name: 'Consumer Spending Boom',
    description: 'Record holiday spending drives consumer and entertainment sectors',
    impacts: {
      Consumer: 0.09,
      Entertainment: 0.08,
      Finance: 0.03,
      Telecom: 0.02,
      Technology: 0.02,
    },
    color: '#ec4899',
  },
];
